name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: testGO
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code into the go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
